# Generated by Django 6.0.2 on 2026-02-23 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_image_focus_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('offensive', 'Offensive / inappropriate'), ('harassment', 'Harassment'), ('irrelevant', 'Irrelevant'), ('other', 'Other')], max_length=32)),
                ('note', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('comment', 'user'), name='unique_user_comment_report')],
            },
        ),
    ]
